:- use_module('day1/day1.pl').
:- use_module('day2/day2.pl').
:- use_module('day3/day3.pl').
:- use_module('day4/day4.pl').
:- use_module('day5/day5.pl').
:- use_module('day6/day6.pl').
:- use_module('day7/day7.pl').
:- use_module('day8/day8.pl').
:- use_module('day9/day9.pl').
:- use_module('day10/day10.pl').
:- use_module('day12/day12.pl').
:- use_module('day13/day13.pl').